version: "3.8"
name: "keycloak"
services:
  kc-data:
    image: postgres:16.2-alpine3.18
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  keycloak:
    image: keycloak/keycloak:24.0
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_PASSWORD=postgres
      - KC_DB_URL=jdbc:postgresql://kc-data:5432/postgres
      - KC_DB_USERNAME=postgres
    depends_on:
      - kc-data
    ports:
      - "4480:8080"
