version: "3.8"
name: "test"
services:
  backend-workspace:
    image: lamlance/trello-backend:workspace-dev
    env_file:
      - ./configs/.env
    environment:
      - GRPC_HOST=0.0.0.0
      - PORT=3000
      - SERVICE_NAME=workspace
      - DB_CONN_STR=mongodb://MONGO_USER:MONGO_123@mongo:27017/trello?authSource=admin
      - KEYCLOAK_AUTH_SERVER_URL=${keycloak_auth_server}
      - KEYCLOAK_REALM=trello
      - KEYCLOAK_CLIENT_ID=trello
      - KEYCLOAK_CLIENT_SECRET=${keycloak_client_secret}
    ports:
      - 3030:3000
      - 3031:3001

  nginx:
    image: nginx:stable-alpine3.17-slim
    ports:
      - 7080:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-workspace
