version: "3.8"
name: "backend"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 7001:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: MONGO_123

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: MONGO_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: MONGO_123
      ME_CONFIG_MONGODB_URL: mongodb://MONGO_USER:MONGO_123@mongo:27017/
