apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubedb
  namespace: demo
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: mongo-sh
                port:
                  number: 27017
            path: /
            pathType: Prefix
